package com.cwc.credit.model.enums;

public enum Bank {
	
	STATE_BANK_OF_INDIA,
	PUNJAB_NATIONAL_BANK,
	BANK_OF_BARODA,
	CANARA_BANK,
	UNION_BANK_OF_INDIA,
	BANK_OF_INDIA,
	CENTRAL_BANK_OF_INDIA,
	INDIAN_BANK,
	INDIAN_OVERSEAS_BANK,
	BANK_OF_MAHARASHTRA,
	ICICI_BANK,
	HDFC_BANK,
	AXIS_BANK,
	KOTAK_MAHINDRA_BANK,
	INDUSIND_BANK,
	YES_BANK,
	RBL_BANK,
	FEDERAL_BANK,
	IDFC_FIRST_BANK,
	BANDHAN_BANK,
	BARODA_UTTAR_PRADESH_GRAMIN_BANK,
	PUNJAB_GRAMIN_BANK,
	KERALA_GRAMIN_BANK,
	PRAGATHI_KRISHNA_GRAMIN_BANK,
	ANDHRA_PRAGATHI_GRAMEENA_BANK,
	PALLAVAN_GRAMA_BANK,
	UTTAR_BANGA_KSHETRIYA_GRAMIN_BANK,
	ASSAM_GRAMIN_VIKASH_BANK,
	MADHYA_BIHAR_GRAMIN_BANK,
	ODISHA_GRAMYA_BANK


}
